
---
title: ""
author: ""
date: '22 ноября 2017 г '
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r clearence, R libraries}
rm(list = ls())

library(ape)
library(reldna)
```


Reading in E. coli K12 genome (GenBank Accesion U00096.2), creating reverse complement genome and tranformation genome into character form 
```{r Reading in E. coli genome}
e.coli_U00096.2_char<-read.GenBank(access.nb = 'U00096.2', as.character = T)$U00096.2
e.coli_U00096.2_string <- paste0(e.coli_U00096.2_char, collapse = '')[[1]]

```
Dynamical properties calculation from within R using octave script translated according to Grinevich et al., 2013
Creating function for dynamical properties calculation

```{r dynchars function }



dynchars<-function(seq, interval_size) {
  if (missing(seq))
    stop("Need to specify sequence (as a vector of chars)")
  
  if (missing(interval_size))
    stop("Need to specify interval size")
  
  if(!is.character(seq))
    stop("Sequence must be a character vector containing A, C, G, T letters only")
  
  seq<-toupper(seq)
  seq<-c(seq, seq[2:(interval_size)])
  
  a<-3.4*10^(-10)
  I<-c(7.6, 4.8, 8.2, 4.1)*10^(-44)
  K<-c(227, 155, 220, 149)*10^(-20)
  V<-c(2.09, 1.43, 3.12, 2.12)*10^(-20)
  tau<-c(127, 99, 140, 84)
  
  csA<-cumsum(seq=='A') 
  csT<-cumsum(seq=='T')
  csG<-cumsum(seq=='G')
  csC<-cumsum(seq=='C')
  
  countA = csA[interval_size:length(csA)]-c(0, csA[1:(length(csA)-interval_size)])
  countT = csT[interval_size:length(csT)]-c(0, csT[1:(length(csT)-interval_size)])
  countG = csG[interval_size:length(csG)]-c(0, csG[1:(length(csG)-interval_size)])
  countC = csC[interval_size:length(csC)]-c(0, csC[1:(length(csC)-interval_size)])
  
  M<-cbind(countA, countT, countG, countC)/interval_size
  M_comp<-cbind(countT, countA, countC, countG)/interval_size
  M_comp<-apply(t(M_comp),1,rev) 
  Is<-as.numeric(M%*%I)#! numeric conversion
  Ks<-as.numeric(M%*%K)
  Vs<-as.numeric(M%*%V)
  
  E01<-(8*(Ks*Vs)^0.5)* 6E23 / 4184
  d1<-((Ks*a^2)/Vs)^(0.5)/a;
  c1<-(Ks*a^2/Is)^0.5
  m1<-E01/c1/6.011E-26
  taus1<-as.numeric(M%*%tau) #!as.numeric conversion
  gc1 = M[,3] + M[,4]
  
  Is<-as.numeric(M%*%I)#! numeric conversion
  Ks<-as.numeric(M%*%K)
  Vs<-as.numeric(M%*%V)
  
  
  E02<- 8*(Ks*Vs)^0.5  * 6E23 / 4184;
  d2<-((Ks*a^2)/Vs)^(0.5)/a;
  c2<-(Ks*a^2/Is)^0.5;
  m2<-E02/c2/6.011E-26;
  taus2<-as.numeric(M_comp%*%tau)
  gc2 = M_comp[,3] + M_comp[,4]
  
  dynchars_return<-list(E01=E01, d1=d1, c1=c1, m1=m1, taus1=taus1, gc1=gc1, E02=E02, d2=d2, c2=c2, m2=m2, taus2=taus2, gc2=gc2)
  
  return(dynchars_return)
  
}
```

```{r Overall characteristics for both bacteria, cache=TRUE}
whole_e.coli_dynchars <- dynchars(e.coli_U00096.2_char, interval_size = 200)
#whole_e.coli_EP <- lseqspline1D(e.coli_U00096.2_string, bound = c(1, nchar(e.coli_U00096.2_string)), width = 1, ref =  1)
#whole_e.coli_geom <- dnaGeom(e.coli_U00096.2_string)

```


```{r EP calculation for psuedo-tss}
pseudo_tss <- seq(0, nchar(e.coli_U00096.2_string), 150)

shifted_by <- 250
extended_e.coli_U00096.2_string <- paste0(
  substr(e.coli_U00096.2_string, nchar(e.coli_U00096.2_string)-shifted_by, nchar(e.coli_U00096.2_string)),
  e.coli_U00096.2_string,
    substr(e.coli_U00096.2_string, 0, shifted_by)
)

library(Biostrings)
reverseComplement_extended_e.coli_U00096.2_string <-as.character(reverseComplement(DNAString(extended_e.coli_U00096.2_string)))

whole_e.coli_EP1 <- c()
zout<- -480:239
for (i in 1:length(pseudo_tss)) {
    p<-lseqspline1D(substr(extended_e.coli_U00096.2_string, pseudo_tss[i]+shifted_by-250, pseudo_tss[i]+shifted_by+150), bound=c(50, 350), ref=251 )
    whole_e.coli_EP1<-cbind(whole_e.coli_EP1, p$mpot[p$x %in% zout])
    #print(str(p$mpot[p$x %in% zout]))
}

whole_e.coli_EP2 <- c()
zout<- -480:239
for (i in 1:length(pseudo_tss)) {
    p<-lseqspline1D(substr(reverseComplement_extended_e.coli_U00096.2_string, pseudo_tss[i]+shifted_by-250, pseudo_tss[i]+shifted_by+150), bound=c(50, 350), ref=251 )
    whole_e.coli_EP2<-cbind(whole_e.coli_EP2, p$mpot[p$x %in% zout])
    print(str(p$mpot[p$x %in% zout]))
}


unique(whole_e.coli_EP1==rev(whole_e.coli_EP2))
str(whole_e.coli_EP1)
str(whole_e.coli_EP2)

write.csv(whole_e.coli_EP1, file = '/home/jane/Документы/Misha/mol_a_2018/different_bacteria_physics_an_text/whole_e.coli_EP_1strand.csv')


write.csv(whole_e.coli_EP2, file = '/home/jane/Документы/Misha/mol_a_2018/different_bacteria_physics_an_text/whole_e.coli_EP_2strand.csv')
```

```{r}
E01 <- scale(whole_e.coli_dynchars$E01)
E02 <- scale(whole_e.coli_dynchars$E02)


d1 <- scale(whole_e.coli_dynchars$d1)
d2 <- scale(whole_e.coli_dynchars$d2)


gc1 <- scale(whole_e.coli_dynchars$gc1)
gc2 <- scale(whole_e.coli_dynchars$gc2)




```

```{r Parallel}
extended_ecoli_string <- extended_e.coli_U00096.2_string
#pseudo_tss <- 1:250000

library(parallel)
library(reldna)
no_cores = detectCores() - 2
cl <- makeCluster(no_cores)

calculate_EP_on_interval <- function(tss_position, extended_string, shifted_by, zout) {
  p <- lseqspline1D(substr(extended_string, tss_position, tss_position+shifted_by+150), bound=c(50, 350), ref=251 )
  return (p$mpot[p$x %in% zout])
}

clusterExport(cl, 'extended_ecoli_string')
clusterExport(cl, 'calculate_EP_on_interval')
clusterEvalQ(cl, {library(reldna)})

#res <- parSapply(cl, X = pseudo_tss, FUN = function(x) calculate_EP_on_interval(x, extended_ecoli_string, 250, -480:239))
#stopCluster(cl)

#save(res, file = '/home/jane/Документы/Misha/mol_a_2018/parsapply_ep_ecoli1strand_1_.rda')
```


```{r By fragments}
bounds <- c(seq(1, nchar(extended_ecoli_string), 250000), nchar(extended_ecoli_string))

for (i in 1:(length(bounds) - 1)){
  pseudo_tss <- bounds[i]:bounds[i+1]
  print(length(pseudo_tss))
  
  res <- parSapply(cl, X = pseudo_tss, FUN = function(x) calculate_EP_on_interval(x, extended_ecoli_string, 250, -480:239))
  
  assign( paste0('sliced_ep_', min(pseudo_tss), '_', max(pseudo_tss)), res)
  
  rm(list = ls())
  save( res, file = paste0('/home/jane/Документы/Misha/mol_a_2018/',  paste0('sliced_ep_', min(pseudo_tss), '_', max(pseudo_tss)), '.rda'))
}
  
#which fragment has highest EP AUC

whole_e.coli_EP_1_250001_sum <- apply(res, 1, sum)
save(whole_e.coli_EP_1_250001_sum, file = '/home/jane/Документы/Misha/mol_a_2018/whole_e.coli_EP_1_250001_sum.rda')
```


